services:
  app:
    build: .
    user: ${CURRENT_UID}
    container_name: fast_auth
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.docker
    command: ["sh", "-c", "python app.py"]
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:16.2
    container_name: postgres_fast_auth
    restart: always
    env_file:
      - .env.docker
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - mynetwork

  redis:
    image: redis:7.2.4
    container_name: redis_fast_auth
    restart: always
    volumes:
      - redis-db-volume:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: True
    name: mynetwork

volumes:
  postgres-db-volume:
