services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: ${CURRENT_UID}
    container_name: fast_auth
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - ./migrations:/migrations
      - ./alembic.ini:/alembic.ini
    command: [
      "sh", "-c",
      "python -m src.cli --upgrade && uvicorn scr.app:app --host 0.0.0.0 --port 8000"
    ]
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:16.2
    container_name: postgres_fast_auth
    restart: always
    environment:
      - DB_HOST=postgres_fast_auth
      - POSTGRES_DB=fast_auth
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    env_file:
      - .env.docker
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - mynetwork

  redis:
    image: redis:7.2.4
    container_name: redis_fast_auth
    restart: always
    volumes:
      - redis-db-volume:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: True
    name: mynetwork

volumes:
  postgres-db-volume:
  redis-db-volume:
